### ISSUE TITLE
Implement unary instructions

### ISSUE THREAD

**Issue by jonathanvdc** [jonathanvdc/dfasm#1]
We don't have any unary instructions yet. We should definitely implement these instructions, though:
- [inc - operator++](http://pdos.csail.mit.edu/6.828/2006/readings/i386/INC.htm)
- [dec - operator--](http://pdos.csail.mit.edu/6.828/2006/readings/i386/DEC.htm)
- [neg - operator-](http://pdos.csail.mit.edu/6.828/2006/readings/i386/NEG.htm)
- [not - operator~](http://pdos.csail.mit.edu/6.828/2006/readings/i386/NOT.htm)

Some of these may have shorter encodings for specific registers (eax or ecx, usually). I suggest we only implement those when feasible, and try to focus on uniformity as much as possible.

Implementing [setcc](http://pdos.csail.mit.edu/6.828/2006/readings/i386/SETcc.htm) would be cool, too.

**Comment by maurisvh** [comment]
These are all implemented now.
