### ISSUE TITLE
Make dfasm process command-line arguments

### ISSUE THREAD

**Issue by jonathanvdc** [jonathanvdc/dfasm#9]
We control dfasm's functionality by changing some flags in dfasm.py every time we want it to behave differently. It'd be great to use command-line arguments instead, as this would prevent changes to the source code.

**Comment by jonathanvdc** [comment]
Input works great!

**Comment by Sibert-Aerts** [comment]
:+1:

**Comment by Sibert-Aerts** [comment]
[:new_moon_with_face:](http://www.imdb.com/title/tt1259571/)
